#  WARNING:
# This file was initially generated by an LLM and adopted with minimal edits.
# Treat it as external boilerplate: review carefully before modifying.  Do not
# assume the implementation reflects project-wide style or design standards.

"""Sync README code blocks from source files.

Usage in README:

<!-- readme-sync path="examples/readme_minimal.py" lang="python" -->
```python
```
<!-- /readme-sync -->
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

_BLOCK_RE = re.compile(
    r"(?P<open><!--\s*readme-sync(?P<attrs>.*?)-->)"
    r"\s*[\n]?"
    r"(?P<fence>```[^\n]*\n.*?```[ \t]*)"
    r"\s*[\n]?"
    r"\n(?P<close><!--\s*/readme-sync\s*-->)",
    re.DOTALL,
)
_ATTR_RE = re.compile(r'(\w+)="([^"]*)"')

_LANGUAGE_BY_SUFFIX = {
    ".py": "python",
    ".sh": "bash",
    ".bash": "bash",
}


class SyncError(RuntimeError):
    """Raised when README synchronization fails."""


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "readme",
        nargs="?",
        default="readme.md",
        help="README file to update. Defaults to readme.md.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with status 1 if README would change.",
    )
    parser.add_argument(
        "--diff",
        action="store_true",
        help="Print unified diff when README would change.",
    )
    parser.add_argument(
        "--resources-root",
        default=".",
        type=Path,
        help="Path to resource root directory",
    )
    return parser.parse_args()


def _parse_attrs(raw: str) -> dict[str, str]:
    attrs = dict(_ATTR_RE.findall(raw))
    if "path" not in attrs:
        msg = 'readme-sync block is missing required path="..." attribute'
        raise SyncError(msg)
    return attrs


def _detect_language(path: Path) -> str:
    return _LANGUAGE_BY_SUFFIX.get(path.suffix.lower(), "text")


def _read_snippet(
    resource_root: Path, attrs: dict[str, str]
) -> tuple[str, str]:
    source_path = (resource_root / attrs["path"]).resolve()

    if not source_path.is_file():
        msg = f"Source file not found: {source_path}"
        raise SyncError(msg)

    snippet = source_path.read_text(encoding="utf-8").rstrip() + "\n"
    language = attrs.get("lang", _detect_language(source_path))
    return language, snippet


def _render_fence(language: str, snippet: str) -> str:
    return f"```{language}\n{snippet}```"


def _sync_text(resource_root: Path, original: str) -> str:
    def replace(match: re.Match[str]) -> str:
        attrs = _parse_attrs(match.group("attrs"))
        language, snippet = _read_snippet(resource_root, attrs)
        fence = _render_fence(language, snippet)
        return f"{match.group('open')}\n\n{fence}\n\n{match.group('close')}"

    updated, n_subs = _BLOCK_RE.subn(replace, original)
    if n_subs == 0:
        msg = "No readme-sync blocks found."
        raise SyncError(msg)
    return updated


def _print_diff(before: str, after: str, readme_path: Path) -> None:
    diff = difflib.unified_diff(
        before.splitlines(keepends=True),
        after.splitlines(keepends=True),
        fromfile=f"a/{readme_path}",
        tofile=f"b/{readme_path}",
    )
    sys.stdout.writelines(diff)


def main() -> int:
    args = _parse_args()
    readme_path = Path(args.readme)

    try:
        original = readme_path.read_text(encoding="utf-8")
        updated = _sync_text(args.resources_root, original)
    except SyncError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    changed = updated != original

    if args.diff and changed:
        _print_diff(original, updated, readme_path)

    if args.check:
        return 1 if changed else 0

    if changed:
        readme_path.write_text(updated, encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
